swagger: '2.0'
info:
  title: Events API
  description: Serves the Clever Events API
  version: 1.2.0
schemes:
  - https
produces:
  - application/json
host: api.clever.com
basePath: /v1.2

x-samples-languages: [
    "curl",
    "node",
    "ruby",
    "python",
    "php",
    "java",
    "go"
  ]

responses:
  BadRequest:
    description: Bad Request
    schema:
      $ref: "#/definitions/BadRequest"

  InternalError:
    description: Internal Error
    schema:
      $ref: "#/definitions/InternalError"

  NotFound:
    description: Entity Not Found
    schema:
      $ref: "#/definitions/NotFound"

security:
  - oauth: []

paths:
  /events:
    get:
      tags: ["Events"]
      description: Returns a list of events
      operationId: getEvents
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: starting_after
        type: string
      - in: query
        name: ending_before
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventsResponse'
        '404':
          $ref: '#/responses/NotFound'

  /events/{id}:
    get:
      tags: ["Events"]
      description: Returns the specific event
      operationId: getEvent
      parameters:
      - in: path
        name: id
        required: true
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventResponse'
        '404':
          $ref: '#/responses/NotFound'

  /teachers/{id}/events:
    get:
      tags: ["Record-specific Events"]
      description: Returns a list of events for a teacher
      operationId: getEventsForTeacher
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: starting_after
        type: string
      - in: query
        name: ending_before
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventsResponse'
        '404':
          $ref: '#/responses/NotFound'

  /students/{id}/events:
    get:
      tags: ["Record-specific Events"]
      description: Returns a list of events for a student
      operationId: getEventsForStudent
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: starting_after
        type: string
      - in: query
        name: ending_before
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventsResponse'
        '404':
          $ref: '#/responses/NotFound'

  /sections/{id}/events:
    get:
      tags: ["Record-specific Events"]
      description: Returns a list of events for a section
      operationId: getEventsForSection
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: starting_after
        type: string
      - in: query
        name: ending_before
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventsResponse'
        '404':
          $ref: '#/responses/NotFound'

  /schools/{id}/events:
    get:
      tags: ["Record-specific Events"]
      description: Returns a list of events for a school
      operationId: getEventsForSchool
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: starting_after
        type: string
      - in: query
        name: ending_before
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventsResponse'
        '404':
          $ref: '#/responses/NotFound'

  /school_admins/{id}/events:
    get:
      tags: ["Record-specific Events"]
      description: Returns a list of events for a school admin
      operationId: getEventsForSchoolAdmin
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: starting_after
        type: string
      - in: query
        name: ending_before
        type: string
      responses:
        '200':
          description: OK Response
          schema:
            $ref: '#/definitions/EventsResponse'
        '404':
          $ref: '#/responses/NotFound'

securityDefinitions:
  oauth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://clever.com/oauth/authorize
    tokenUrl: https://clever.com/oauth/tokens

definitions:
  NotFound:
    type: object
    properties:
      message:
        type: string

  InternalError:
    type: object
    properties:
      message:
        type: string

  BadRequest:
    type: object
    properties:
      message:
        type: string

  EventsResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/EventResponse"

  EventResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/Event"

  Event:
    type: object
    discriminator: type
    properties:
      type:
        type: string
        x-validation: true
      id:
        type: string
        x-validation: true
    required:
    - type

  students.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/StudentObject"
          previous_attributes:
            additionalProperties:
              type: object

  students.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/StudentObject"

  students.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/StudentObject"

  teachers.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/TeacherObject"
          previous_attributes:
            additionalProperties:
              type: object

  teachers.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/TeacherObject"

  teachers.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/TeacherObject"

  sections.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SectionObject"
          previous_attributes:
            additionalProperties:
              type: object

  sections.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SectionObject"

  sections.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SectionObject"

  schools.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SchoolObject"
          previous_attributes:
            additionalProperties:
              type: object

  schools.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SchoolObject"

  schools.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SchoolObject"

  schooladmins.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SchoolAdminObject"
          previous_attributes:
            additionalProperties:
              type: object

  schooladmins.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SchoolAdminObject"

  schooladmins.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/SchoolAdminObject"

  studentcontacts.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/StudentContactObject"
          previous_attributes:
            additionalProperties:
              type: object

  studentcontacts.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/StudentContactObject"

  studentcontacts.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/StudentContactObject"

  districts.updated:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/DistrictObject"
          previous_attributes:
            additionalProperties:
              type: object

  districts.created:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/DistrictObject"

  districts.deleted:
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data:
            $ref: "#/definitions/DistrictObject"

  Student:
    type: object
    properties:
      id:
        type: string
      created:
        type: string
        format: datetime
        x-nullable: true
      district:
        type: string
      dob:
        type: string
        format: datetime
        x-nullable: true
      email:
        type: string
        x-nullable: true
      gender:
        type: string
        x-nullable: true
      grade:
        type: string
        x-nullable: true
      hispanic_ethnicity:
        type: string
        x-nullable: true
      last_modified:
        type: string
        format: datetime
        x-nullable: true
      location:
        $ref: "#/definitions/Location"
      name:
        $ref: "#/definitions/Name"
      race:
        type: string
        x-nullable: true
      school:
        type: string
      schools:
        type: array
        items:
          type: string
      sis_id:
        type: string
        x-nullable: true
      state_id:
        type: string
        x-nullable: true
      student_number:
        type: string
        x-nullable: true

  StudentContact:
    type: object
    properties:
      id:
        type: string
      district:
        type: string
      email:
        type: string
        x-nullable: true
      name:
        type: string
        x-nullable: true
      phone:
        type: string
        x-nullable: true
      phone_type:
        type: string
        x-nullable: true
      relationship:
        type: string
        x-nullable: true
      student:
        type: string
      type:
        type: string
        x-nullable: true

  Teacher:
    type: object
    properties:
      id:
        type: string
      created:
        type: string
        format: datetime
        x-nullable: true
      district:
        type: string
      email:
        type: string
        x-nullable: true
      last_modified:
        type: string
        format: datetime
        x-nullable: true
      name:
        $ref: "#/definitions/Name"
      school:
        type: string
      schools:
        type: array
        items:
          type: string
      sis_id:
        type: string
        x-nullable: true
      state_id:
        type: string
        x-nullable: true
      teacher_number:
        type: string
        x-nullable: true
      title:
        type: string
        x-nullable: true

  Section:
    type: object
    properties:
      id:
        type: string
      course_description:
        type: string
        x-nullable: true
      course_name:
        type: string
        x-nullable: true
      course_number:
        type: string
        x-nullable: true
      created:
        type: string
        format: datetime
        x-nullable: true
      district:
        type: string
      grade:
        type: string
        x-nullable: true
      last_modified:
        type: string
        format: datetime
        x-nullable: true
      name:
        type: string
        x-nullable: true
      period:
        type: string
        x-nullable: true
      school:
        type: string
      section_number:
        type: string
        x-nullable: true
      sis_id:
        type: string
        x-nullable: true
      students:
        type: array
        items:
          type: string
      subject:
        type: string
        x-nullable: true
      teacher:
        type: string
        x-nullable: true
      teachers:
        type: array
        items:
          type: string
      term:
        $ref: "#/definitions/Term"

  School:
    type: object
    properties:
      id:
        type: string
      created:
        type: string
        format: datetime
        x-nullable: true
      district:
        type: string
      high_grade:
        type: string
        x-nullable: true
      last_modified:
        type: string
        format: datetime
        x-nullable: true
      location:
        $ref: "#/definitions/Location"
      low_grade:
        type: string
        x-nullable: true
      name:
        type: string
        x-nullable: true
      nces_id:
        type: string
        x-nullable: true
      phone:
        type: string
        x-nullable: true
      principal:
        $ref: "#/definitions/Principal"
      school_number:
        type: string
        x-nullable: true
      sis_id:
        type: string
        x-nullable: true
      state_id:
        type: string
        x-nullable: true
      mdr_number:
        type: string
        x-nullable: true

  SchoolAdmin:
    type: object
    properties:
      id:
        type: string
      district:
        type: string
      email:
        type: string
        x-nullable: true
      name:
        $ref: "#/definitions/Name"
      schools:
        type: array
        items:
          type: string
      staff_id:
        type: string
        x-nullable: true
      title:
        type: string
        x-nullable: true

  District:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      mdr_number:
        type: string
        x-nullable: true

  Name:
    type: object
    properties:
      first:
        type: string
        x-nullable: true
      middle:
        type: string
        x-nullable: true
      last:
        type: string
        x-nullable: true

  Location:
    type: object
    properties:
      address:
        type: string
        x-nullable: true
      city:
        type: string
        x-nullable: true
      state:
        type: string
        x-nullable: true
      zip:
        type: string
        x-nullable: true
      lat:
        type: string
        x-nullable: true
      lon:
        type: string
        x-nullable: true

  Term:
    type: object
    properties:
      name:
        type: string
        x-nullable: true
      start_date:
        type: string
        format: datetime
        x-nullable: true
      end_date:
        type: string
        format: datetime
        x-nullable: true

  Principal:
    type: object
    properties:
      name:
        type: string
        x-nullable: true
      email:
        type: string
        x-nullable: true

  StudentObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/Student"

  TeacherObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/Teacher"

  SchoolAdminObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/SchoolAdmin"

  SectionObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/Section"

  StudentContactObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/StudentContact"

  SchoolObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/School"

  DistrictObject:
    type: object
    properties:
      object:
        $ref: "#/definitions/District"
