basePath: /v2.0
definitions:
  BadRequest:
    properties:
      message:
        type: string
    type: object
  InternalError:
    properties:
      message:
        type: string
    type: object
  Me:
    properties:
      district:
        type: string
        x-validation: true
      id:
        type: string
        x-validation: true
      type:
        type: string
        x-validation: true
    type: object
  MeResponse:
    properties:
      data:
        $ref: '#/definitions/Me'
    type: object
  Unauthorized:
    properties:
      message:
        type: string
    type: object
host: api.clever.com
info:
  description: The Clever Identity API
  title: Identity API
  version: 2.0.0
paths:
  /me:
    get:
      description: Returns the owner of the user token
      operationId: getMe
      responses:
        "200":
          description: OK Response
          schema:
            $ref: '#/definitions/MeResponse'
        "401":
          $ref: '#/responses/Unauthorized'
      tags:
      - Identity
produces:
- application/json
responses:
  BadRequest:
    description: Bad Request
    schema:
      $ref: '#/definitions/BadRequest'
  InternalError:
    description: Internal Error
    schema:
      $ref: '#/definitions/InternalError'
  NotFound:
    description: Entity Not Found
    schema:
      $ref: '#/definitions/NotFound'
  Unauthorized:
    description: Unauthorized
    schema:
      $ef: '#/definitions/Unauthorized'
schemes:
- https
security:
- oauth: []
securityDefinitions:
  oauth:
    authorizationUrl: https://clever.com/oauth/authorize
    flow: accessCode
    tokenUrl: https://clever.com/oauth/tokens
    type: oauth2
    x-default: TEST_TOKEN
swagger: "2.0"
x-samples-languages:
- curl
- node
- ruby
- python
- php
- java
- go
